spring:
  datasource:
    username: test
    url: jdbc\:postgresql\://localhost\:5432/test?autosave\=conservative&loggerLevel\=OFF
    password: test

## Application properties configuration
app:
  logLevel: DEBUG
  provider:
    silverflow:
      url: https://www.silverflow.com